---
- name: Install K3s Master Node
  hosts: k3s_master
  become: yes
  tasks:
    - name: Install curl if missing
      apt:
        name: curl
        state: present
        update_cache: yes

    - name: Install K3s master
      shell: |
        curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Wait for K3s to be ready
      shell: kubectl get nodes
      register: kubectl_output
      retries: 5
      delay: 10
      until: "'Ready' in kubectl_output.stdout"

    - name: Fetch K3s node-token
      shell: cat /var/lib/rancher/k3s/server/node-token
      register: k3s_token
      changed_when: false

    - name: Save K3s token locally for worker nodes
      local_action:
        copy content="{{ k3s_token.stdout }}" dest="./k3s_token"
